person:
  boss: true
  birth: 2021/10/03
  age: 19
  pet:
    name: xiaohua
    age: 4
  interests:
    - baseketball
    - football
    - tannies
  animal: [xiaomao,xiaogou]
  score:
    english: 100
    Chinese: 99

  salaries:
    [9999.78,9999.99]
  allPets:
    sick:
      - {name: kk,age: 11}
      - name: ss
        age: 1
      - name: tt
        age: 2
      - name: sdf
        age: 2
    healty:
      - {name: lili,age: 3}
      - {name: aaaa,age: 5}
#  username: zhangshan
  username: ssss


server:
  port: 9000




###指定静态资源的 访问前缀  会导致配置功能失效
#spring:
#  mvc:
#    static-path-pattern: res/**


#指定扫描哪个文件夹中的静态资源
spring:
  web:
    resources:
      static-locations: classpath:/mystatic/
      add-mappings: true # false使所有的静态资源都不生效,禁用所有的静态资源的访问
#  mvc:
#    static-path-pattern: res/**
      cache:
        period: 11000
  mvc:
    hiddenmethod:
      filter:
        enabled: true # 开启页面表单的Rest功能，前后端分离，就不用开启了，


